(() => {
 'use strict';
 const client=window.efirAdminClient,$=id=>document.getElementById(id),root=$('management');
 const kinds=['landings','apps','promos','subscriptions'];
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=v=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('ru-RU'):'—';
 const active=v=>!!v&&new Date(v)>new Date();
 const pageSize=50,storageKey='efir-admin-management-v1';
 const sections={
  landings:{placeholder:'Ник, адрес страницы, email или ID пользователя',create:'',empty:'Лендингов пока нет',filters:[['published','Опубликованные'],['draft','Черновики'],['disabled','Отключённые']]},
  apps:{placeholder:'Название или ID приложения',create:'Добавить приложение',empty:'Приложений пока нет',filters:[['published','В каталоге'],['hidden','Скрытые'],['disabled','Запуск отключён'],['exclusive','Эксклюзивные']]},
  promos:{placeholder:'Промокод',create:'Создать промокод',empty:'Промокодов пока нет',filters:[['active','Доступны для активации'],['disabled','Отключённые'],['expired','Истёк срок'],['exhausted','Лимит исчерпан']]},
  subscriptions:{placeholder:'Имя, email или ID пользователя',create:'',empty:'Пользователи не найдены',filters:[['active','С активной подпиской'],['trial','С активным пробным доступом'],['expiring','Подписка истекает за 7 дней'],['inactive','Без активного доступа']]}
 };
 let kind='',appliedSearch='',offset=0,items=[],total=0,sequence=0,ready=false,busy=false,loading=false,dialog=null,dirty=false,returnFocus=null,loadedAt=null;
 let viewState={};try{const stored=JSON.parse(sessionStorage.getItem(storageKey)||'{}');if(stored&&typeof stored==='object'&&!Array.isArray(stored))viewState=stored;}catch{}
 const errors={DATA_CHANGED:'Данные уже изменились. Закройте окно, обновите список и повторите.',LANDING_CHANGED:'Лендинг уже изменился. Закройте окно и обновите список.',ADMIN_REQUIRED:'Нет прав администратора.',SLUG_TAKEN:'Адрес занят другим лендингом.',SLUG_RESERVED:'Этот адрес зарезервирован.',INVALID_PHOTO:'Не удалось сохранить фото.',PHOTO_AND_BUTTON_REQUIRED:'Для публикации нужны фото и хотя бы одна кнопка.',LIMIT_BELOW_USED:'Лимит не может быть меньше числа активаций.',NO_ACTIVE_SUBSCRIPTION:'Активной подписки нет.',INVALID_DAYS:'Укажите целое число дней.',RULES_REQUIRED:'Добавьте текст правил.',INVALID_LINK:'Проверьте ссылки: нужны полные адреса https:// или http://.'};
 function errorText(e,fallback='Не удалось сохранить. Проверьте поля и подключение.'){return Object.entries(errors).find(([key])=>String(e?.message||'').includes(key))?.[1]||fallback;}
 async function rpc(name,args){const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
 function notice(text){$('management-status').textContent=text;}
 function rowStatus(label,on){return '<span class="control-badge '+(on?'on':'')+'">'+label+'</span>';}
 const field=(name,label,value='',type='text',extra='')=>'<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" '+extra+'></label>';
 const area=(name,label,value='',extra='')=>'<label class="wide">'+label+'<textarea name="'+name+'" '+extra+'>'+esc(value)+'</textarea></label>';
 const check=(name,label,value)=>'<label class="control-check"><input type="checkbox" name="'+name+'" '+(value?'checked':'')+'>'+label+'</label>';
 const button=(text,action,cls='ghost')=>'<button type="button" class="'+cls+'" data-action="'+action+'">'+text+'</button>';
 const filterLabel=document.createElement('label');filterLabel.className='control-page-filter';filterLabel.innerHTML='Статус на этой странице<select id="management-page-filter" aria-describedby="management-page-note"><option value="">Все статусы</option></select>';
 $('management-filter').append(filterLabel);
 const pageNote=document.createElement('p');pageNote.id='management-page-note';pageNote.className='control-note';pageNote.textContent='Поиск — по всему разделу. Фильтр статуса — только среди 50 записей текущей страницы.';$('management-filter').append(pageNote);
 const clearSearch=document.createElement('button');clearSearch.type='button';clearSearch.className='ghost';clearSearch.textContent='Сбросить';clearSearch.id='management-clear';$('management-filter').append(clearSearch);
 const summary=document.createElement('div');summary.className='control-summary';summary.setAttribute('aria-label','Сводка текущей страницы');$('management-list').before(summary);
 function remember(){if(!kind)return;viewState[kind]={search:$('management-search').value,filter:$('management-page-filter').value};try{sessionStorage.setItem(storageKey,JSON.stringify(viewState));}catch{}}
 function configure(){const section=sections[kind],state=viewState[kind]||{};$('management-search').placeholder=section.placeholder;$('management-search').value=typeof state.search==='string'?state.search:'';appliedSearch=$('management-search').value.trim();$('management-page-filter').innerHTML='<option value="">Все статусы</option>'+section.filters.map(([value,label])=>'<option value="'+value+'">'+label+'</option>').join('');$('management-page-filter').value=section.filters.some(([value])=>value===state.filter)?state.filter:'';$('management-create').hidden=!section.create;$('management-create').textContent=section.create||'Создать';}
 function route(){const next=location.hash.slice(1);if(!kinds.includes(next)){sequence++;loading=false;return;}if(next!==kind){remember();kind=next;offset=0;configure();}if(ready)load();}
 function pagination(){ $('management-prev').disabled=loading||offset===0;$('management-next').disabled=loading||!items.length||offset+pageSize>=total;$('management-refresh').disabled=loading;$('management-page-filter').disabled=loading||!loadedAt;$('management-page').textContent=loading?'Загрузка…':total?`${offset+1}–${Math.min(offset+items.length,total)} из ${total}`:'Нет записей'; }
 async function load(successMessage=''){
  if(!ready||!kinds.includes(kind)||root.hidden)return false;
  const request=++sequence;loading=true;loadedAt=null;notice('Загрузка…');$('management-list').setAttribute('aria-busy','true');$('management-list').innerHTML='<div class="empty"><strong>Загружаем записи…</strong></div>';summary.replaceChildren();pagination();
  try{const data=await rpc('admin_control_list',{p_kind:kind,p_search:appliedSearch,p_offset:offset});if(request!==sequence)return false;
   if(!Array.isArray(data?.items)||!Number.isFinite(Number(data.total)))throw Error('INVALID_RESPONSE');
   items=data.items;total=Math.max(0,Number(data.total));
   if(offset&&offset>=total){offset=total?Math.floor((total-1)/pageSize)*pageSize:0;return await load(successMessage);}
   loading=false;loadedAt=new Date();render();if(successMessage)notice(successMessage+' '+resultText());return true;
  }catch(e){if(request===sequence){items=[];total=0;loading=false;pagination();const message=/admin_control_list|PGRST202/.test(e?.message||'')?'Раздел ещё не подключён к базе. Повторите после обновления сервера.':errorText(e,'Не удалось загрузить записи. Проверьте подключение и повторите.');notice(message);$('management-list').innerHTML='<div class="empty control-error"><strong>Список недоступен</strong><p>'+esc(message)+'</p><button type="button" class="ghost" data-retry>Повторить загрузку</button></div>';$('management-list').querySelector('[data-retry]').onclick=()=>load();}return false;}
  finally{if(request===sequence){loading=false;$('management-list').removeAttribute('aria-busy');pagination();}}
 }
 function promoState(item){if(!item.is_active)return 'disabled';if(item.expires_at&&!active(item.expires_at))return 'expired';if(item.max_redemptions!=null&&item.redemptions_count>=item.max_redemptions)return 'exhausted';return 'active';}
 function matches(item,filter){if(!filter)return true;if(kind==='landings'){const state=item.is_disabled||!item.editor_access?'disabled':item.published?'published':'draft';return state===filter;}if(kind==='apps')return filter==='exclusive'?item.is_exclusive:filter==='disabled'?item.is_disabled:filter==='published'?item.is_published&&!item.is_disabled:!item.is_published&&!item.is_disabled;if(kind==='promos')return promoState(item)===filter;if(kind==='subscriptions')return filter==='active'?active(item.expires_at):filter==='trial'?active(item.trial?.expires_at):filter==='expiring'?active(item.expires_at)&&Date.parse(item.expires_at)-Date.now()<=7*86400000:!active(item.expires_at)&&!active(item.trial?.expires_at);return true;}
 function resultText(){const filter=$('management-page-filter').value;return 'Найдено: '+total+(filter?' · Показано на странице: '+items.filter(item=>matches(item,filter)).length+' из '+items.length:'')+(loadedAt?' · Обновлено '+loadedAt.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}):'');}
 function renderSummary(){summary.innerHTML='<span>На этой странице: <strong>'+items.length+'</strong></span>'+sections[kind].filters.map(([value,label])=>'<span>'+esc(label)+': <strong>'+items.filter(item=>matches(item,value)).length+'</strong></span>').join('');summary.hidden=!items.length;}
 function render(){
  pagination();renderSummary();notice(resultText());
  const filter=$('management-page-filter').value;
  $('management-list').innerHTML=items.map((item,index)=>{
   if(!matches(item,filter))return '';
   let title,subtitle,status,detail='',extra='',editLabel='Управлять';
   if(kind==='landings'){title=item.draft?.nickname||'Без имени';subtitle=item.email||item.user_id;status=rowStatus(item.is_disabled||!item.editor_access?'Отключён':item.published?'Опубликован':'Черновик',!!item.published&&!item.is_disabled&&item.editor_access);detail='<p>Черновик: /'+esc(item.draft?.slug)+' · '+(item.published?'<a href="/'+encodeURIComponent(item.published.slug)+'" target="_blank" rel="noopener">Открыть /'+esc(item.published.slug)+' ↗</a>':'Публичной страницы нет')+'</p><p>Изменён: '+date(item.updated_at)+(!item.editor_access?' · У владельца нет доступа к редактору':'')+'</p>';editLabel='Редактировать';}
   if(kind==='apps'){title=item.name;subtitle=item.id;status=rowStatus(item.is_disabled?'Запуск отключён':item.is_published?'В каталоге':'Скрыто',item.is_published&&!item.is_disabled)+(item.is_exclusive?rowStatus('Эксклюзив',true):'');detail='<p>'+esc(item.description||'Описание не заполнено')+'</p><p>Файл: '+esc(item.executable||'—')+' · В галерее: '+(item.media?.length||0)+'</p>';extra=item.owner&&item.repo?'<a class="ghost" href="https://github.com/'+encodeURIComponent(item.owner)+'/'+encodeURIComponent(item.repo)+'/releases" target="_blank" rel="noopener">Релизы ↗</a>':'';editLabel='Редактировать';}
   if(kind==='promos'){const state=promoState(item);title=item.code;subtitle=item.days+' дней доступа';status=rowStatus({active:'Доступен для активации',disabled:'Отключён',expired:'Срок истёк',exhausted:'Лимит исчерпан'}[state],state==='active');detail='<p>Активаций: '+item.redemptions_count+' / '+(item.max_redemptions??'без лимита')+(item.max_redemptions!=null?' · Осталось: '+Math.max(0,item.max_redemptions-item.redemptions_count):'')+'</p><p>Срок: '+(item.expires_at?date(item.expires_at):'без ограничения')+'</p>';extra='<button type="button" class="ghost" data-copy="'+index+'">Скопировать код</button>';editLabel='Настроить';}
   if(kind==='subscriptions'){title=item.name||item.email||'Пользователь';subtitle=item.email||item.user_id;status=rowStatus(active(item.expires_at)?'Подписка активна':'Без активной подписки',active(item.expires_at))+(active(item.trial?.expires_at)?rowStatus('Пробный доступ активен',true):'');detail='<p>Подписка до: '+date(item.expires_at)+(active(item.expires_at)?' · Осталось дней: '+Math.ceil((Date.parse(item.expires_at)-Date.now())/86400000):'')+(item.trial?'<br>Пробный доступ до: '+date(item.trial.expires_at)+' · Код: '+esc(item.trial.promo_code):'')+'</p><p>Записей в истории: '+(item.subscriptions?.length||0)+'</p>';editLabel='Изменить срок';}
   return '<article class="control-row"><div><strong>'+esc(title)+'</strong><small>'+esc(subtitle)+'</small>'+detail+'<div class="control-statuses">'+status+'</div></div><div class="control-row-actions"><button type="button" class="ghost" data-edit="'+index+'" aria-label="'+editLabel+': '+esc(title)+'">'+editLabel+'</button>'+extra+'</div></article>';
  }).join('')||'<div class="empty"><strong>'+(items.length?'На этой странице нет записей с выбранным статусом':$('management-search').value.trim()?'Ничего не найдено':sections[kind].empty)+'</strong><p>'+(items.length?'Сбросьте статус или перейдите на другую страницу.':$('management-search').value.trim()?'Попробуйте другой запрос или сбросьте поиск.':'Новые записи появятся здесь.')+'</p>'+(filter||$('management-search').value.trim()?'<button type="button" class="ghost" data-reset>Сбросить фильтры</button>':'')+'</div>';
  root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(items[Number(b.dataset.edit)]));
  root.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(items[Number(b.dataset.copy)].code);notice('Промокод скопирован.');}catch{notice('Не удалось скопировать. Выделите код в списке и скопируйте вручную.');}});
  root.querySelector('[data-reset]')?.addEventListener('click',resetFilters);
 }
 function close(force=false){if(busy)return false;if(dirty&&!force&&!window.confirm('Закрыть без сохранения изменений?'))return false;dialog?.close();dialog?.remove();dialog=null;dirty=false;if(returnFocus?.isConnected)returnFocus.focus();returnFocus=null;return true;}
 function open(title,content){
  returnFocus=document.activeElement;dirty=false;dialog=document.createElement('dialog');dialog.className='control-dialog';dialog.setAttribute('aria-labelledby','control-dialog-title');
  dialog.innerHTML='<form class="control-form"><header><div><h2 id="control-dialog-title">'+esc(title)+'</h2><p class="control-dirty" aria-live="polite"></p></div><button type="button" class="ghost" data-close aria-label="Закрыть">×</button></header><fieldset class="control-fields">'+content+'</fieldset><p class="control-message" role="status" aria-live="polite" aria-atomic="true" tabindex="-1"></p></form>';
  document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>close();dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.querySelector('form').addEventListener('input',markDirty);dialog.querySelector('form').addEventListener('change',markDirty);dialog.showModal();dialog.querySelector('input:not([readonly]),textarea,select')?.focus();return dialog.querySelector('form');
 }
 function markDirty(){dirty=true;if(dialog)dialog.querySelector('.control-dirty').textContent='Есть несохранённые изменения';}
 async function save(action){
  if(busy||!dialog)return;const savingDialog=dialog;busy=true;savingDialog.setAttribute('aria-busy','true');savingDialog.querySelector('fieldset').disabled=true;savingDialog.querySelector('[data-close]').disabled=true;savingDialog.querySelector('.control-message').classList.remove('is-error');savingDialog.querySelector('.control-message').textContent='Сохраняем…';
  try{await action();if(dialog!==savingDialog)return;busy=false;close(true);const refreshed=await load('Изменения сохранены.');if(ready&&!refreshed)notice('Изменения сохранены, но список не обновился. Нажмите «Повторить загрузку».');if(!root.hidden)$('management-search').focus();}
  catch(e){if(dialog===savingDialog){const message=dialog.querySelector('.control-message');message.textContent=errorText(e);message.classList.add('is-error');dialog.querySelector('fieldset').disabled=false;dialog.querySelector('[data-close]').disabled=false;message.focus();}}
  finally{if(dialog===savingDialog){dialog.removeAttribute('aria-busy');busy=false;}}
 }
 function edit(item){if(dialog)return;if(kind==='apps')editApp(item);if(kind==='promos')editPromo(item);if(kind==='landings')editLanding(item);if(kind==='subscriptions')editSubscription(item);}
 function editApp(item){
  const app=item||{id:'',name:'',is_published:false,is_exclusive:false,media:[]};
  const form=open(item?'Приложение · '+app.name:'Новое приложение',field('id','ID приложения',app.id,'text','required pattern="[a-z0-9][a-z0-9_-]{0,63}" '+(item?'readonly':''))+field('name','Название',app.name,'text','required maxlength="100"')+area('description','Краткое описание',app.description,'maxlength="1000"')+area('long_description','Полное описание',app.long_description,'maxlength="20000"')+field('owner','Владелец GitHub',app.owner,'text','required')+field('repo','Репозиторий GitHub',app.repo,'text','required')+field('executable','Запускаемый файл .exe',app.executable,'text','required')+field('icon','Резервная иконка',app.icon)+field('icon_url','Адрес иконки',app.icon_url,'url')+field('cover_url','Адрес обложки',app.cover_url,'url')+check('is_published','Показывать в каталоге',app.is_published)+check('is_exclusive','Эксклюзивное приложение',app.is_exclusive)+check('is_disabled','Отключить запуск для всех пользователей',app.is_disabled)+'<p class="wide control-note">Скрытие убирает приложение из общего каталога. Персональными доступами можно управлять в разделе «Пользователи».</p><div class="wide"><h3>Галерея</h3><div id="control-media"></div>'+button('Добавить изображение или видео','media-add')+'</div><div class="wide control-actions"><button class="primary">Сохранить приложение</button></div>');
  let media=structuredClone(app.media||[]);
  function drawMedia(){form.querySelector('#control-media').innerHTML=media.map((m,i)=>'<div class="control-media"><select aria-label="Тип медиа '+(i+1)+'"><option value="image" '+(m.kind==='image'?'selected':'')+'>Изображение</option><option value="video" '+(m.kind==='video'?'selected':'')+'>Видео</option></select><input type="url" aria-label="Адрес медиа '+(i+1)+'" value="'+esc(m.url)+'" required><button type="button" class="ghost" aria-label="Удалить медиа '+(i+1)+'" data-remove="'+i+'">×</button></div>').join('');form.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{readMedia();media.splice(+b.dataset.remove,1);markDirty();drawMedia();});}
  function readMedia(){media=[...form.querySelectorAll('.control-media')].map(r=>({kind:r.querySelector('select').value,url:r.querySelector('input').value.trim()}));}
  drawMedia();form.querySelector('[data-action="media-add"]').onclick=()=>{readMedia();if(media.length>=30)return;media.push({url:'',kind:'image'});markDirty();drawMedia();};
  form.onsubmit=e=>{e.preventDefault();readMedia();const data=Object.fromEntries(new FormData(form));data.is_published=form.elements.is_published.checked;data.is_exclusive=form.elements.is_exclusive.checked;data.is_disabled=form.elements.is_disabled.checked;data.media=media;save(()=>rpc('admin_control_app',{p_document:data,p_revision:app.admin_revision??null}));};
 }
 function editPromo(item){
  const p=item||{code:'',days:7,is_active:true};const local=p.expires_at?new Date(new Date(p.expires_at)-new Date(p.expires_at).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
  const form=open(item?'Промокод · '+p.code:'Новый промокод',field('code','Промокод',p.code,'text','required pattern="[A-Za-z0-9_-]{3,64}" '+(item?'readonly':''))+field('days','Дней пробного доступа',p.days,'number','required min="1" max="365" step="1"')+field('max_redemptions','Лимит активаций (пусто — без лимита)',p.max_redemptions,'number','min="1" step="1"')+field('expires_at','Действует до (ваше местное время)',local,'datetime-local')+check('is_active','Разрешить активацию',p.is_active)+'<p class="wide control-note">Пробный промокод доступен каждому пользователю один раз. Отключение кода не забирает уже выданные дни. Активаций: '+(p.redemptions_count||0)+'.</p><div class="wide control-actions"><button class="primary">Сохранить промокод</button></div>');
  form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.days=Number(data.days);data.max_redemptions=data.max_redemptions?Number(data.max_redemptions):null;data.expires_at=data.expires_at?new Date(data.expires_at).toISOString():null;data.is_active=form.elements.is_active.checked;save(()=>rpc('admin_control_promo',{p_document:data,p_revision:p.admin_revision??null}));};
 }
 function editLanding(item){
  let doc=structuredClone(item.draft);const form=open('Лендинг · '+(item.email||doc.nickname),'<p class="wide control-note">Редактируется черновик. «Опубликовать» применит его к странице. Отключённая страница останется отключённой до отдельного включения.</p>'+field('nickname','Ник',String(doc.nickname).toUpperCase(),'text','required maxlength="32"')+field('slug','Адрес страницы',doc.slug,'text','required pattern="[a-z0-9][a-z0-9_-]{2,39}"')+'<div class="wide control-actions">'+button(item.is_disabled?'Включить страницу':'Отключить страницу','toggle')+button('Снять с публикации','unpublish')+(item.published?'<a class="ghost" target="_blank" rel="noopener" href="/'+esc(item.published.slug)+'">Открыть страницу ↗</a>':'')+'</div><div class="wide"><h3>Кнопки и ссылки</h3><div id="control-links"></div>'+button('Добавить кнопку','link-add')+'</div>'+check('rulesEnabled','Показывать правила',doc.rulesEnabled)+area('rulesText','Текст правил',doc.rulesText,'maxlength="10000"')+'<div class="wide control-actions"><button class="ghost" name="mode" value="draft">Сохранить черновик</button><button class="primary" name="mode" value="publish">Опубликовать</button></div>');
  let pendingPhoto=null,photoPreview='',previewTimer=null,previewRevision=0;
  const links=form.querySelector('#control-links');
  const photoField=document.createElement('label');photoField.className='wide';photoField.innerHTML='Заменить фотографию (PNG, до 5 МБ)<input type="file" accept="image/png,.png" name="portrait">';
  form.querySelector('fieldset').prepend(photoField);
  const frame=document.createElement('iframe');frame.className='control-preview wide';frame.title='Предпросмотр лендинга';frame.src='/admin-landing-preview.html';frame.setAttribute('sandbox','allow-scripts allow-same-origin');form.querySelector('fieldset').append(frame);
  function readDocument(){readLinks();doc.nickname=form.elements.nickname.value.trim().toUpperCase().slice(0,32);doc.slug=form.elements.slug.value.trim();doc.rulesEnabled=form.elements.rulesEnabled.checked;doc.rulesText=form.elements.rulesText.value;}
  function preview(){if(!dialog)return;readDocument();frame.contentWindow.postMessage({type:'efir-landing-preview',document:doc,photo:photoPreview,editing:true,revision:++previewRevision},location.origin);}
  const layoutEvent=e=>{if(e.source!==frame.contentWindow||e.origin!==location.origin||busy||e.data?.type!=='efir-landing-layout'||e.data.revision!==previewRevision)return;doc.layout=e.data.layout;markDirty();};
  window.addEventListener('message',layoutEvent);dialog.addEventListener('close',()=>{clearTimeout(previewTimer);window.removeEventListener('message',layoutEvent);});
  frame.onload=preview;form.addEventListener('input',()=>{clearTimeout(previewTimer);previewTimer=setTimeout(preview,180);});
  photoField.querySelector('input').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>5242880||file.type!=='image/png')throw Error();const signature=new Uint8Array(await file.slice(0,8).arrayBuffer());if(signature.join(',')!=='137,80,78,71,13,10,26,10')throw Error();const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const image=new Image();image.src=data;await image.decode();if(Math.max(image.naturalWidth,image.naturalHeight)>6000)throw Error();pendingPhoto=file;photoPreview=data;markDirty();preview();}catch{e.target.value='';form.querySelector('.control-message').textContent='Выберите PNG до 5 МБ, не больше 6000 пикселей по стороне.';}};

  function readLinks(){doc.items=[...links.children].map(r=>({id:r.dataset.id,type:r.querySelector('[name="type"]').value,title:r.querySelector('[name="title"]').value,subtitle:r.querySelector('[name="subtitle"]').value,value:r.querySelector('[name="value"]').value}));}
  function drawLinks(){links.innerHTML=doc.items.map((l,i)=>'<article class="control-link" data-id="'+esc(l.id||crypto.randomUUID().replaceAll('-',''))+'"><header><strong>Кнопка '+(i+1)+'</strong><div>'+button('↑','up')+button('↓','down')+button('×','remove')+'</div></header><label>Действие<select name="type"><option value="link" '+(l.type==='link'?'selected':'')+'>Открыть ссылку</option><option value="copy" '+(l.type==='copy'?'selected':'')+'>Скопировать текст</option></select></label>'+field('title','Название',l.title,'text','required maxlength="80"')+field('subtitle','Подпись',l.subtitle,'text','maxlength="160"')+area('value','Ссылка или текст',l.value,'required maxlength="2048"')+'</article>').join('');[...links.children].forEach((r,i)=>{r.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{readLinks();const a=b.dataset.action;if(a==='remove')doc.items.splice(i,1);else{const n=i+(a==='up'?-1:1);if(n<0||n>=doc.items.length)return;[doc.items[i],doc.items[n]]=[doc.items[n],doc.items[i]];}markDirty();drawLinks();preview();});});}
  drawLinks();form.querySelector('[data-action="link-add"]').onclick=()=>{readLinks();if(doc.items.length>=24)return;doc.items.push({type:'link',title:'',subtitle:'',value:''});markDirty();drawLinks();preview();};
  form.querySelector('[data-action="toggle"]').onclick=()=>{if(dirty&&!window.confirm('Изменить статус и закрыть несохранённые правки?'))return;save(()=>rpc('admin_control_landing',{p_user_id:item.user_id,p_revision:item.revision,p_action:item.is_disabled?'enable':'disable'}));};
  form.querySelector('[data-action="unpublish"]').disabled=!item.published;form.querySelector('[data-action="unpublish"]').onclick=()=>{if(window.confirm('Снять страницу с публикации? Черновик сохранится.'+(dirty?' Несохранённые правки в этом окне будут потеряны.':'')))save(()=>rpc('admin_control_landing',{p_user_id:item.user_id,p_revision:item.revision,p_action:'unpublish'}));};
  form.onsubmit=e=>{e.preventDefault();readLinks();doc.nickname=form.elements.nickname.value.trim().toUpperCase().slice(0,32);doc.slug=form.elements.slug.value.trim();doc.rulesEnabled=form.elements.rulesEnabled.checked;doc.rulesText=form.elements.rulesText.value;const action=e.submitter?.value||'draft';save(async()=>{if(pendingPhoto){const {data:{session}}=await client.auth.getSession();if(!session)throw Error('ADMIN_REQUIRED');const path=session.user.id+'/'+crypto.randomUUID()+'.png';const {error}=await client.storage.from('creator-portraits').upload(path,pendingPhoto,{contentType:'image/png',upsert:false});if(error)throw error;doc.photo=path;pendingPhoto=null;}await rpc('admin_control_landing',{p_user_id:item.user_id,p_revision:item.revision,p_action:action,p_document:doc});});};
 }
 function editSubscription(user){
  user={...user,subscriptions:user.subscriptions||[]};const scopes=[...new Set(['all',...user.subscriptions.map(s=>s.app_id)])];
  const form=open('Подписка · '+(user.email||user.user_id),'<p class="wide control-note">Добавление продлевает оставшийся срок, вычитание сокращает его. История сохраняется. Персональные доступы к приложениям управляются отдельно в «Пользователях».</p><label class="wide">Тип доступа<select name="scope">'+scopes.map(s=>'<option value="'+esc(s)+'">'+(s==='all'?'Подписка на все приложения':s==='tiktimer'?'Общая подписка (старый тариф TIMER)':esc(s))+'</option>').join('')+(user.trial?'<option value="@trial">Пробный доступ · '+esc(user.trial.promo_code)+'</option>':'')+'</select></label><p class="wide control-expiry"></p>'+field('days','Количество дней',30,'number','required min="1" max="36500" step="1"')+'<div class="wide control-actions">'+button('Добавить дни','add','primary')+button('Вычесть дни','subtract')+button('Отозвать весь срок','revoke')+'</div><details class="wide"><summary>История подписок ('+user.subscriptions.length+')</summary><div class="control-history">'+user.subscriptions.map(s=>'<p><strong>'+esc(s.source)+' · '+esc(s.app_id)+'</strong><br>'+date(s.starts_at)+' → '+date(s.expires_at)+'</p>').join('')+'</div></details>');
  function selected(){const scope=form.elements.scope.value;const rows=user.subscriptions.filter(s=>s.app_id===scope);return {trial:scope==='@trial',scope,expiry:scope==='@trial'?user.trial.expires_at:rows.reduce((v,s)=>!v||new Date(s.expires_at)>new Date(v)?s.expires_at:v,null)};}
  const projection=document.createElement('p');projection.className='wide control-projection';projection.setAttribute('aria-live','polite');form.querySelector('.control-expiry').after(projection);
  function update(){const s=selected(),days=Number(form.elements.days.value),base=Math.max(Date.now(),Date.parse(s.expiry)||0);projection.textContent=Number.isInteger(days)&&days>0&&days<=36500?'После добавления '+days+' дн.: '+date(new Date(base+days*86400000).toISOString())+(active(s.expiry)?' · После вычитания: '+date(new Date(Math.max(Date.now(),base-days*86400000)).toISOString()):''):'';form.querySelector('.control-expiry').textContent='Действует до: '+date(s.expiry);form.querySelector('[data-action="subtract"]').disabled=!active(s.expiry);form.querySelector('[data-action="revoke"]').disabled=!active(s.expiry);}
  form.elements.scope.onchange=update;form.elements.days.addEventListener('input',update);update();form.onsubmit=e=>e.preventDefault();
  form.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(busy)return;const action=b.dataset.action;if(action!=='revoke'&&!form.reportValidity())return;const s=selected();const days=action==='revoke'?-36500:Number(form.elements.days.value)*(action==='subtract'?-1:1);if(days<0&&!window.confirm((action==='revoke'?'Отозвать весь оставшийся срок':'Вычесть '+Math.abs(days)+' дней')+' у '+(user.email||user.user_id)+'?'))return;save(()=>rpc('admin_control_subscription',{p_user_id:user.user_id,p_days:days,p_expected:s.expiry,p_kind:s.trial?'trial':'subscription',p_scope:s.trial?'all':s.scope}));});
 }
 function resetFilters(){$('management-search').value='';$('management-page-filter').value='';appliedSearch='';offset=0;remember();load();}
 $('management-filter').onsubmit=e=>{e.preventDefault();offset=0;appliedSearch=$('management-search').value.trim();remember();load();};$('management-refresh').onclick=()=>load();
 $('management-search').addEventListener('input',remember);$('management-page-filter').onchange=()=>{remember();if(!loading)render();};clearSearch.onclick=resetFilters;
 $('management-create').onclick=()=>edit(null);$('management-prev').onclick=()=>{if(loading||offset===0)return;offset=Math.max(0,offset-pageSize);load();};$('management-next').onclick=()=>{if(loading||offset+pageSize>=total)return;offset+=pageSize;load();};
 window.addEventListener('hashchange',route);window.addEventListener('efir-admin-ready',()=>{ready=true;route();});window.addEventListener('efir-admin-closed',()=>{ready=false;sequence++;loading=false;busy=false;items=[];total=0;loadedAt=null;viewState={};kind='';appliedSearch='';$('management-search').value='';try{sessionStorage.removeItem(storageKey);}catch{}root.querySelector('#management-list').replaceChildren();summary.replaceChildren();if(dialog){dialog.close();dialog.remove();dialog=null;dirty=false;returnFocus=null;}});
 window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
 ready=!!window.efirAdminReady;route();
})();
