(() => {
 'use strict';
 const client=window.efirAdminClient,$=id=>document.getElementById(id),root=$('management');
 const kinds=['landings','apps','promos','subscriptions'];
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=v=>v?new Date(v).toLocaleString('ru-RU'):'—';
 const active=v=>v&&new Date(v)>new Date();
 let kind='',offset=0,items=[],total=0,sequence=0,ready=false,busy=false,dialog=null,dirty=false;
 const errors={DATA_CHANGED:'Данные уже изменились. Закройте окно, обновите список и повторите.',LANDING_CHANGED:'Лендинг уже изменился. Закройте окно и обновите список.',ADMIN_REQUIRED:'Нет прав администратора.',SLUG_TAKEN:'Адрес занят другим лендингом.',SLUG_RESERVED:'Этот адрес зарезервирован.',INVALID_PHOTO:'Не удалось сохранить фото.',PHOTO_AND_BUTTON_REQUIRED:'Для публикации нужны фото и хотя бы одна кнопка.',LIMIT_BELOW_USED:'Лимит не может быть меньше числа активаций.',NO_ACTIVE_SUBSCRIPTION:'Активной подписки нет.',INVALID_DAYS:'Укажите целое число дней.',RULES_REQUIRED:'Добавьте текст правил.',INVALID_LINK:'Проверьте ссылки: нужны полные адреса https:// или http://.'};
 function errorText(e){return Object.entries(errors).find(([key])=>String(e.message).includes(key))?.[1]||'Не удалось сохранить. Проверьте поля и подключение.';}
 async function rpc(name,args){const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
 function notice(text){$('management-status').textContent=text;}
 function rowStatus(label,on){return '<span class="control-badge '+(on?'on':'')+'">'+label+'</span>';}
 const field=(name,label,value='',type='text',extra='')=>'<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" '+extra+'></label>';
 const area=(name,label,value='',extra='')=>'<label class="wide">'+label+'<textarea name="'+name+'" '+extra+'>'+esc(value)+'</textarea></label>';
 const check=(name,label,value)=>'<label class="control-check"><input type="checkbox" name="'+name+'" '+(value?'checked':'')+'>'+label+'</label>';
 const button=(text,action,cls='ghost')=>'<button type="button" class="'+cls+'" data-action="'+action+'">'+text+'</button>';
 function route(){const next=location.hash.slice(1);if(!kinds.includes(next)){sequence++;return;}if(next!==kind){kind=next;offset=0;$('management-search').value='';}if(ready)load();}
 async function load(){
  if(!ready||!kinds.includes(kind)||root.hidden)return;
  const request=++sequence;notice('Загрузка…');$('management-list').setAttribute('aria-busy','true');
  try{const data=await rpc('admin_control_list',{p_kind:kind,p_search:$('management-search').value.trim(),p_offset:offset});if(request!==sequence)return;
   items=data.items||[];total=data.total;render();notice('Найдено: '+total);
  }catch(e){if(request===sequence){items=[];$('management-list').replaceChildren();notice(/admin_control_list|PGRST202/.test(e.message)?'Раздел ещё не подключён к базе. Обновите страницу позже.':errorText(e));}}
  finally{if(request===sequence)$('management-list').removeAttribute('aria-busy');}
 }
 function render(){
  $('management-create').hidden=!['apps','promos'].includes(kind);
  $('management-prev').disabled=offset===0;$('management-next').disabled=offset+50>=total;
  $('management-page').textContent=total?`${offset+1}–${Math.min(offset+50,total)} из ${total}`:'0';
  $('management-list').innerHTML=items.map((item,index)=>{
   let title,subtitle,status,detail='';
   if(kind==='landings'){title=item.draft.nickname||'Без имени';subtitle=item.email||item.user_id;status=rowStatus(item.is_disabled||!item.editor_access?'Отключён':item.published?'Опубликован':'Черновик',!!item.published&&!item.is_disabled&&item.editor_access);detail='<p>Черновик: /'+esc(item.draft.slug)+' · '+(item.published?'<a href="/'+esc(item.published.slug)+'" target="_blank" rel="noopener">Открыть /'+esc(item.published.slug)+' ↗</a>':'Публичной страницы нет')+'</p>';}
   if(kind==='apps'){title=item.name;subtitle=item.id;status=rowStatus(item.is_disabled?'Запуск отключён':item.is_published?'В каталоге':'Скрыто',item.is_published&&!item.is_disabled)+(item.is_exclusive?rowStatus('Эксклюзив',true):'');detail='<p>'+esc(item.description)+'</p>';}
   if(kind==='promos'){title=item.code;subtitle=item.days+' дней доступа';status=rowStatus(item.is_active&&(!item.expires_at||active(item.expires_at))&&(item.max_redemptions===null||item.redemptions_count<item.max_redemptions)?'Активен':'Неактивен',item.is_active);detail='<p>Активаций: '+item.redemptions_count+' / '+(item.max_redemptions??'без лимита')+' · Срок: '+date(item.expires_at)+'</p>';}
   if(kind==='subscriptions'){title=item.name||item.email||'Пользователь';subtitle=item.email||item.user_id;status=rowStatus(active(item.expires_at)?'Подписка активна':'Без активной подписки',active(item.expires_at));detail='<p>Подписка до: '+date(item.expires_at)+(item.trial?' · Пробный доступ до: '+date(item.trial.expires_at):'')+'</p>';}
   return '<article class="control-row"><div><strong>'+esc(title)+'</strong><small>'+esc(subtitle)+'</small>'+detail+'<div class="control-statuses">'+status+'</div></div><button class="ghost" data-edit="'+index+'">Управлять</button></article>';
  }).join('')||'<div class="empty"><strong>Ничего не найдено</strong><p>Попробуйте другой запрос.</p></div>';
  root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(items[Number(b.dataset.edit)]));
 }
 function close(force=false){if(busy)return;if(dirty&&!force&&!window.confirm('Закрыть без сохранения изменений?'))return;dialog?.close();dialog?.remove();dialog=null;dirty=false;}
 function open(title,content){
  dialog=document.createElement('dialog');dialog.className='control-dialog';dialog.setAttribute('aria-label',title);
  dialog.innerHTML='<form class="control-form"><header><h2>'+esc(title)+'</h2><button type="button" class="ghost" data-close aria-label="Закрыть">×</button></header><fieldset class="control-fields">'+content+'</fieldset><p class="control-message" role="status" aria-live="polite"></p></form>';
  document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>close();dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.querySelector('form').oninput=()=>dirty=true;dialog.showModal();return dialog.querySelector('form');
 }
 async function save(action){
  if(busy)return;busy=true;dialog.querySelector('fieldset').disabled=true;dialog.querySelector('[data-close]').disabled=true;dialog.querySelector('.control-message').textContent='Сохраняем…';
  try{await action();busy=false;close(true);await load();notice('Изменения сохранены.');}
  catch(e){if(dialog){dialog.querySelector('.control-message').textContent=errorText(e);dialog.querySelector('fieldset').disabled=false;dialog.querySelector('[data-close]').disabled=false;}}
  finally{busy=false;}
 }
 function edit(item){if(dialog)return;if(kind==='apps')editApp(item);if(kind==='promos')editPromo(item);if(kind==='landings')editLanding(item);if(kind==='subscriptions')editSubscription(item);}
 function editApp(item){
  const app=item||{id:'',name:'',is_published:false,is_exclusive:false,media:[]};
  const form=open(item?'Приложение · '+app.name:'Новое приложение',field('id','ID приложения',app.id,'text','required pattern="[a-z0-9][a-z0-9_-]{0,63}" '+(item?'readonly':''))+field('name','Название',app.name,'text','required maxlength="100"')+area('description','Краткое описание',app.description,'maxlength="1000"')+area('long_description','Полное описание',app.long_description,'maxlength="20000"')+field('owner','Владелец GitHub',app.owner,'text','required')+field('repo','Репозиторий GitHub',app.repo,'text','required')+field('executable','Запускаемый файл .exe',app.executable,'text','required')+field('icon','Резервная иконка',app.icon)+field('icon_url','Адрес иконки',app.icon_url,'url')+field('cover_url','Адрес обложки',app.cover_url,'url')+check('is_published','Показывать в каталоге',app.is_published)+check('is_exclusive','Эксклюзивное приложение',app.is_exclusive)+check('is_disabled','Отключить запуск для всех пользователей',app.is_disabled)+'<p class="wide control-note">Скрытие убирает приложение из общего каталога. Персональными доступами можно управлять в разделе «Пользователи».</p><div class="wide"><h3>Галерея</h3><div id="control-media"></div>'+button('Добавить изображение или видео','media-add')+'</div><div class="wide control-actions"><button class="primary">Сохранить приложение</button></div>');
  let media=structuredClone(app.media||[]);
  function drawMedia(){form.querySelector('#control-media').innerHTML=media.map((m,i)=>'<div class="control-media"><select aria-label="Тип медиа '+(i+1)+'"><option value="image" '+(m.kind==='image'?'selected':'')+'>Изображение</option><option value="video" '+(m.kind==='video'?'selected':'')+'>Видео</option></select><input type="url" aria-label="Адрес медиа '+(i+1)+'" value="'+esc(m.url)+'" required><button type="button" class="ghost" aria-label="Удалить медиа '+(i+1)+'" data-remove="'+i+'">×</button></div>').join('');form.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{readMedia();media.splice(+b.dataset.remove,1);dirty=true;drawMedia();});}
  function readMedia(){media=[...form.querySelectorAll('.control-media')].map(r=>({kind:r.querySelector('select').value,url:r.querySelector('input').value.trim()}));}
  drawMedia();form.querySelector('[data-action="media-add"]').onclick=()=>{readMedia();if(media.length>=30)return;media.push({url:'',kind:'image'});dirty=true;drawMedia();};
  form.onsubmit=e=>{e.preventDefault();readMedia();const data=Object.fromEntries(new FormData(form));data.is_published=form.elements.is_published.checked;data.is_exclusive=form.elements.is_exclusive.checked;data.is_disabled=form.elements.is_disabled.checked;data.media=media;save(()=>rpc('admin_control_app',{p_document:data,p_revision:app.admin_revision??null}));};
 }
 function editPromo(item){
  const p=item||{code:'',days:7,is_active:true};const local=p.expires_at?new Date(new Date(p.expires_at)-new Date(p.expires_at).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
  const form=open(item?'Промокод · '+p.code:'Новый промокод',field('code','Промокод',p.code,'text','required pattern="[A-Za-z0-9_-]{3,64}" '+(item?'readonly':''))+field('days','Дней пробного доступа',p.days,'number','required min="1" max="365" step="1"')+field('max_redemptions','Лимит активаций (пусто — без лимита)',p.max_redemptions,'number','min="1" step="1"')+field('expires_at','Действует до (ваше местное время)',local,'datetime-local')+check('is_active','Разрешить активацию',p.is_active)+'<p class="wide control-note">Пробный промокод доступен каждому пользователю один раз. Отключение кода не забирает уже выданные дни. Активаций: '+(p.redemptions_count||0)+'.</p><div class="wide control-actions"><button class="primary">Сохранить промокод</button></div>');
  form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.days=Number(data.days);data.max_redemptions=data.max_redemptions?Number(data.max_redemptions):null;data.expires_at=data.expires_at?new Date(data.expires_at).toISOString():null;data.is_active=form.elements.is_active.checked;save(()=>rpc('admin_control_promo',{p_document:data,p_revision:p.admin_revision??null}));};
 }
 function editLanding(item){
  let doc=structuredClone(item.draft);const form=open('Лендинг · '+(item.email||doc.nickname),'<p class="wide control-note">Редактируется черновик. «Опубликовать» применит его к странице. Отключённая страница останется отключённой до отдельного включения.</p>'+field('nickname','Ник',String(doc.nickname).toUpperCase(),'text','required maxlength="32"')+field('slug','Адрес страницы',doc.slug,'text','required pattern="[a-z0-9][a-z0-9_-]{2,39}"')+'<div class="wide control-actions">'+button(item.is_disabled?'Включить страницу':'Отключить страницу','toggle')+button('Снять с публикации','unpublish')+(item.published?'<a class="ghost" target="_blank" rel="noopener" href="/'+esc(item.published.slug)+'">Открыть страницу ↗</a>':'')+'</div><div class="wide"><h3>Кнопки и ссылки</h3><div id="control-links"></div>'+button('Добавить кнопку','link-add')+'</div>'+check('rulesEnabled','Показывать правила',doc.rulesEnabled)+area('rulesText','Текст правил',doc.rulesText,'maxlength="10000"')+'<div class="wide control-actions"><button class="ghost" name="mode" value="draft">Сохранить черновик</button><button class="primary" name="mode" value="publish">Опубликовать</button></div>');
  let pendingPhoto=null,photoPreview='',previewTimer=null,previewRevision=0;
  const links=form.querySelector('#control-links');
  const photoField=document.createElement('label');photoField.className='wide';photoField.innerHTML='Заменить фотографию (PNG, до 5 МБ)<input type="file" accept="image/png,.png" name="portrait">';
  form.querySelector('fieldset').prepend(photoField);
  const frame=document.createElement('iframe');frame.className='control-preview wide';frame.title='Предпросмотр лендинга';frame.src='/admin-landing-preview.html';frame.setAttribute('sandbox','allow-scripts allow-same-origin');form.querySelector('fieldset').append(frame);
  function readDocument(){readLinks();doc.nickname=form.elements.nickname.value.trim().toUpperCase().slice(0,32);doc.slug=form.elements.slug.value.trim();doc.rulesEnabled=form.elements.rulesEnabled.checked;doc.rulesText=form.elements.rulesText.value;}
  function preview(){if(!dialog)return;readDocument();frame.contentWindow.postMessage({type:'efir-landing-preview',document:doc,photo:photoPreview,editing:true,revision:++previewRevision},location.origin);}
  const layoutEvent=e=>{if(e.source!==frame.contentWindow||e.origin!==location.origin||busy||e.data?.type!=='efir-landing-layout'||e.data.revision!==previewRevision)return;doc.layout=e.data.layout;dirty=true;};
  window.addEventListener('message',layoutEvent);dialog.addEventListener('close',()=>{clearTimeout(previewTimer);window.removeEventListener('message',layoutEvent);});
  frame.onload=preview;form.addEventListener('input',()=>{clearTimeout(previewTimer);previewTimer=setTimeout(preview,180);});
  photoField.querySelector('input').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>5242880||file.type!=='image/png')throw Error();const signature=new Uint8Array(await file.slice(0,8).arrayBuffer());if(signature.join(',')!=='137,80,78,71,13,10,26,10')throw Error();const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const image=new Image();image.src=data;await image.decode();if(Math.max(image.naturalWidth,image.naturalHeight)>6000)throw Error();pendingPhoto=file;photoPreview=data;dirty=true;preview();}catch{e.target.value='';form.querySelector('.control-message').textContent='Выберите PNG до 5 МБ, не больше 6000 пикселей по стороне.';}};

  function readLinks(){doc.items=[...links.children].map(r=>({id:r.dataset.id,type:r.querySelector('[name="type"]').value,title:r.querySelector('[name="title"]').value,subtitle:r.querySelector('[name="subtitle"]').value,value:r.querySelector('[name="value"]').value}));}
  function drawLinks(){links.innerHTML=doc.items.map((l,i)=>'<article class="control-link" data-id="'+esc(l.id||crypto.randomUUID().replaceAll('-',''))+'"><header><strong>Кнопка '+(i+1)+'</strong><div>'+button('↑','up')+button('↓','down')+button('×','remove')+'</div></header><label>Действие<select name="type"><option value="link" '+(l.type==='link'?'selected':'')+'>Открыть ссылку</option><option value="copy" '+(l.type==='copy'?'selected':'')+'>Скопировать текст</option></select></label>'+field('title','Название',l.title,'text','required maxlength="80"')+field('subtitle','Подпись',l.subtitle,'text','maxlength="160"')+area('value','Ссылка или текст',l.value,'required maxlength="2048"')+'</article>').join('');[...links.children].forEach((r,i)=>{r.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{readLinks();const a=b.dataset.action;if(a==='remove')doc.items.splice(i,1);else{const n=i+(a==='up'?-1:1);if(n<0||n>=doc.items.length)return;[doc.items[i],doc.items[n]]=[doc.items[n],doc.items[i]];}dirty=true;drawLinks();preview();});});}
  drawLinks();form.querySelector('[data-action="link-add"]').onclick=()=>{readLinks();if(doc.items.length>=24)return;doc.items.push({type:'link',title:'',subtitle:'',value:''});dirty=true;drawLinks();preview();};
  form.querySelector('[data-action="toggle"]').onclick=()=>{if(dirty&&!window.confirm('Изменить статус и закрыть несохранённые правки?'))return;save(()=>rpc('admin_control_landing',{p_user_id:item.user_id,p_revision:item.revision,p_action:item.is_disabled?'enable':'disable'}));};
  form.querySelector('[data-action="unpublish"]').onclick=()=>{if(window.confirm('Снять страницу с публикации? Черновик сохранится.'))save(()=>rpc('admin_control_landing',{p_user_id:item.user_id,p_revision:item.revision,p_action:'unpublish'}));};
  form.onsubmit=e=>{e.preventDefault();readLinks();doc.nickname=form.elements.nickname.value.trim().toUpperCase().slice(0,32);doc.slug=form.elements.slug.value.trim();doc.rulesEnabled=form.elements.rulesEnabled.checked;doc.rulesText=form.elements.rulesText.value;const action=e.submitter?.value||'draft';save(async()=>{if(pendingPhoto){const {data:{session}}=await client.auth.getSession();if(!session)throw Error('ADMIN_REQUIRED');const path=session.user.id+'/'+crypto.randomUUID()+'.png';const {error}=await client.storage.from('creator-portraits').upload(path,pendingPhoto,{contentType:'image/png',upsert:false});if(error)throw error;doc.photo=path;pendingPhoto=null;}await rpc('admin_control_landing',{p_user_id:item.user_id,p_revision:item.revision,p_action:action,p_document:doc});});};
 }
 function editSubscription(user){
  const scopes=[...new Set(['all',...user.subscriptions.map(s=>s.app_id)])];
  const form=open('Подписка · '+(user.email||user.user_id),'<p class="wide control-note">Добавление продлевает оставшийся срок, вычитание сокращает его. История сохраняется. Персональные доступы к приложениям управляются отдельно в «Пользователях».</p><label class="wide">Тип доступа<select name="scope">'+scopes.map(s=>'<option value="'+esc(s)+'">'+(s==='all'?'Подписка на все приложения':s==='tiktimer'?'Общая подписка (старый тариф TIMER)':esc(s))+'</option>').join('')+(user.trial?'<option value="@trial">Пробный доступ · '+esc(user.trial.promo_code)+'</option>':'')+'</select></label><p class="wide control-expiry"></p>'+field('days','Количество дней',30,'number','required min="1" max="36500" step="1"')+'<div class="wide control-actions">'+button('Добавить дни','add','primary')+button('Вычесть дни','subtract')+button('Отозвать весь срок','revoke')+'</div><details class="wide"><summary>История подписок ('+user.subscriptions.length+')</summary><div class="control-history">'+user.subscriptions.map(s=>'<p><strong>'+esc(s.source)+' · '+esc(s.app_id)+'</strong><br>'+date(s.starts_at)+' → '+date(s.expires_at)+'</p>').join('')+'</div></details>');
  function selected(){const scope=form.elements.scope.value;const rows=user.subscriptions.filter(s=>s.app_id===scope);return {trial:scope==='@trial',scope,expiry:scope==='@trial'?user.trial.expires_at:rows.reduce((v,s)=>!v||new Date(s.expires_at)>new Date(v)?s.expires_at:v,null)};}
  function update(){const s=selected();form.querySelector('.control-expiry').textContent='Действует до: '+date(s.expiry);form.querySelector('[data-action="subtract"]').disabled=!active(s.expiry);form.querySelector('[data-action="revoke"]').disabled=!active(s.expiry);}
  form.elements.scope.onchange=update;update();form.onsubmit=e=>e.preventDefault();
  form.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(!form.reportValidity())return;const s=selected(),action=b.dataset.action;const days=action==='revoke'?-36500:Number(form.elements.days.value)*(action==='subtract'?-1:1);if(days<0&&!window.confirm((action==='revoke'?'Отозвать весь оставшийся срок':'Вычесть '+Math.abs(days)+' дней')+' у '+(user.email||user.user_id)+'?'))return;save(()=>rpc('admin_control_subscription',{p_user_id:user.user_id,p_days:days,p_expected:s.expiry,p_kind:s.trial?'trial':'subscription',p_scope:s.trial?'all':s.scope}));});
 }
 $('management-filter').onsubmit=e=>{e.preventDefault();offset=0;load();};$('management-refresh').onclick=load;
 $('management-create').onclick=()=>edit(null);$('management-prev').onclick=()=>{offset=Math.max(0,offset-50);load();};$('management-next').onclick=()=>{offset+=50;load();};
 window.addEventListener('hashchange',route);window.addEventListener('efir-admin-ready',()=>{ready=true;route();});window.addEventListener('efir-admin-closed',()=>{ready=false;sequence++;items=[];root.querySelector('#management-list').replaceChildren();if(dialog){dialog.close();dialog.remove();dialog=null;dirty=false;}});
 window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
 ready=!!window.efirAdminReady;route();
})();
