(()=>{const client=window.efirAdminClient,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=n=>Number(n||0).toLocaleString('ru-RU'),hours=n=>(Number(n||0)/3600).toFixed(2)+' ч';let last=null,seq=0;
 $('analytics-from').value=new Date(Date.now()-30*86400000).toISOString().slice(0,10);$('analytics-to').value=new Date().toISOString().slice(0,10);
 const table=(headers,rows)=>'<table><thead><tr>'+headers.map(v=>'<th>'+v+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
 async function load(){const id=++seq;$('analytics-status').textContent='Загрузка…';const params={p_from:$('analytics-from').value+'T00:00:00Z',p_to:$('analytics-to').value+'T23:59:59Z',p_user:$('analytics-user').value||null};const {data,error}=await client.rpc('admin_stream_analytics',params);if(id!==seq)return;if(error){$('analytics-status').textContent='Не удалось загрузить статистику: '+error.message;return;}last=data;$('analytics-status').textContent=data.streams.length===1000?'Показаны последние 1000 эфиров. Сузьте период для подробностей.':'Обновлено '+new Date().toLocaleTimeString('ru-RU');const users=new Map(data.users.map(u=>[u.id,u]));if(!params.p_user){const select=$('analytics-user');select.replaceChildren(new Option('Все пользователи',''),...data.users.map(u=>new Option(u.name||u.email,u.id)));}
 $('analytics-summary').innerHTML=[['Время приложений',hours(data.apps.reduce((s,r)=>s+Number(r.seconds),0))],['Эфиров',num(data.streams.length)],['Алмазов',num(data.streams.reduce((s,r)=>s+Number(r.diamonds),0))],['Лаунчеров онлайн',num(data.users.filter(u=>u.online).length)]].map(([label,value])=>'<div><strong>'+value+'</strong><span>'+label+'</span></div>').join('');
 $('analytics-usage').innerHTML=table(['Пользователь','Приложение','Время'],data.apps.map(a=>{const u=users.get(a.user_id)||{};return [esc(u.name||u.email||a.user_id)+'<small>'+esc(u.email)+'</small>',esc(a.app_id),hours(a.seconds)];}));
 $('analytics-streams').innerHTML=table(['Стример / аккаунт','Начало (местное время)','Наблюдался','Средний онлайн','Пик','Алмазы','Подарки','Лайки','Подписки'],data.streams.map(s=>{const u=users.get(s.user_id)||{};return [(s.avatar?.startsWith('https://')?'<img loading="lazy" alt="" referrerpolicy="no-referrer" src="'+esc(s.avatar)+'">':'')+esc(s.nickname||s.username)+'<small>@'+esc(s.username)+' · '+esc(u.email||s.user_id)+'</small><small>'+esc([...new Set((s.apps||[]).flat())].join(', '))+'</small>',esc(new Date(s.started_at).toLocaleString('ru-RU')),hours(s.seconds),s.average_viewers===null?'Нет данных':num(s.average_viewers),num(s.peak_viewers),num(s.diamonds),num(s.gifts),num(s.likes),num(s.follows)];}));
 }
 $('analytics-filter').onsubmit=e=>{e.preventDefault();load();};$('analytics-export').onclick=()=>{if(!last)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(last,null,2)],{type:'application/json'}));a.download='efir-statistics.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 async function session(s){if(!s){$('analytics').hidden=true;last=null;seq++;return;}const {data}=await client.rpc('is_efir_admin');$('analytics').hidden=!data;if(data)load();}
 client.auth.getSession().then(({data})=>session(data.session));client.auth.onAuthStateChange((_,s)=>setTimeout(()=>session(s),0));
})();
