-- Apply after admin-control.sql, creator-landings-v3.sql and tribute-telegram-switch.sql.
-- Referral visibility is installed separately by referral-catalog.sql. No access grants change here.
begin;
create table if not exists public.referral_settings (
 id boolean primary key default true check(id), rate_bps integer not null default 2000 check(rate_bps between 0 and 10000), revision integer not null default 0
);
insert into public.referral_settings(id) values(true) on conflict do nothing;
create table if not exists public.referral_partners (
 user_id uuid primary key references auth.users(id), enabled boolean not null default true,
 rate_bps integer check(rate_bps between 0 and 10000), note text not null default '' check(length(note)<=2000),
 revision integer not null default 0, created_at timestamptz not null default now()
);
-- History fixes the effective percentage at verified webhook receipt, including delayed Telegram links.
create table if not exists public.referral_rate_history (
 id bigint generated by default as identity primary key, partner_id uuid references public.referral_partners(user_id),
 rate_bps integer check(rate_bps between 0 and 10000), changed_at timestamptz not null default now()
);
create index if not exists referral_rate_history_lookup on public.referral_rate_history(partner_id,changed_at desc,id desc);
create table if not exists public.referral_attributions (
 user_id uuid primary key references auth.users(id), partner_id uuid not null references public.referral_partners(user_id),
 code text not null, created_at timestamptz not null default now(), check(user_id<>partner_id)
);
-- Client-reported device hashes are a supplemental review signal, never an identity or rejection rule.
alter table public.referral_attributions add column if not exists device_hash text check(device_hash is null or device_hash ~ '^[a-f0-9]{64}$');
create index if not exists referral_attributions_partner on public.referral_attributions(partner_id);
create table if not exists public.referral_payments (
 payment_key text primary key, telegram_id text not null, subscription_id text not null, period_id text not null,
 paid_at timestamptz not null, expires_at timestamptz not null,
 gross_amount numeric(20,2) not null check(gross_amount>0), net_amount numeric(20,2) not null check(net_amount>=0),
 currency text not null check(currency in ('EUR','USD','RUB')), buyer_id uuid references auth.users(id),
 partner_id uuid references public.referral_partners(user_id), code text, rate_bps integer check(rate_bps between 0 and 10000),
 commission numeric(20,2) not null default 0 check(commission>=0), reversed numeric(20,2) not null default 0 check(reversed>=0 and reversed<=commission),
 resolution text not null default 'unlinked', received_at timestamptz not null default now()
);
create index if not exists referral_payments_partner on public.referral_payments(partner_id,paid_at desc);
create table if not exists public.referral_payouts (
 id uuid primary key, partner_id uuid not null references public.referral_partners(user_id),
 currency text not null check(currency in ('EUR','USD','RUB')), amount numeric(20,2) not null check(amount>0),
 note text not null check(length(trim(note)) between 1 and 2000), admin_user_id uuid not null references auth.users(id), created_at timestamptz not null default now()
);
create table if not exists public.referral_reversals (
 id uuid primary key, payment_key text not null unique references public.referral_payments(payment_key),
 amount numeric(20,2) not null, note text not null, admin_user_id uuid not null references auth.users(id), created_at timestamptz not null default now()
);
alter table public.referral_settings enable row level security;
alter table public.referral_partners enable row level security;
alter table public.referral_attributions enable row level security;
alter table public.referral_payments enable row level security;
alter table public.referral_payouts enable row level security;
alter table public.referral_reversals enable row level security;
alter table public.referral_rate_history enable row level security;
revoke all on public.referral_rate_history from public,anon,authenticated;
grant all on public.referral_rate_history to service_role;
revoke all on public.referral_settings,public.referral_partners,public.referral_attributions,public.referral_payments,public.referral_payouts,public.referral_reversals from public,anon,authenticated;
grant all on public.referral_settings,public.referral_partners,public.referral_attributions,public.referral_payments,public.referral_payouts,public.referral_reversals to service_role;

create or replace function public.referral_rate_track() returns trigger language plpgsql security definer set search_path='' as $$
begin
 if tg_op='INSERT' or old.rate_bps is distinct from new.rate_bps then
  if tg_table_name='referral_partners' then insert into public.referral_rate_history(partner_id,rate_bps) values(new.user_id,new.rate_bps);
  else insert into public.referral_rate_history(partner_id,rate_bps) values(null,new.rate_bps);end if;
 end if;
 return new;
end $$;
drop trigger if exists referral_partner_rate_track on public.referral_partners;
create trigger referral_partner_rate_track after insert or update on public.referral_partners for each row execute function public.referral_rate_track();
drop trigger if exists referral_default_rate_track on public.referral_settings;
create trigger referral_default_rate_track after update on public.referral_settings for each row execute function public.referral_rate_track();
insert into public.referral_rate_history(partner_id,rate_bps) select null,rate_bps from public.referral_settings where id and not exists(select 1 from public.referral_rate_history where partner_id is null);
insert into public.referral_rate_history(partner_id,rate_bps) select p.user_id,p.rate_bps from public.referral_partners p where not exists(select 1 from public.referral_rate_history h where h.partner_id=p.user_id);

create or replace function public.referral_landing_access_sync() returns trigger language plpgsql security definer set search_path='' as $$
begin
 -- Existing partner suspension and custom percentage survive access toggles.
 insert into public.referral_partners(user_id) values(new.user_id) on conflict do nothing;
 return new;
end $$;
drop trigger if exists referral_landing_access_sync on public.landing_access;
create trigger referral_landing_access_sync after insert on public.landing_access for each row execute function public.referral_landing_access_sync();
insert into public.referral_partners(user_id) select user_id from public.landing_access on conflict do nothing;

create or replace function public.referral_partner_active(p_user uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.referral_partners r join public.landing_access a on a.user_id=r.user_id join public.creator_landings c on c.user_id=r.user_id where r.user_id=p_user and r.enabled and not c.is_disabled and c.published is not null);
$$;
create or replace function public.efir_referral_status(p_user uuid) returns jsonb language sql stable security definer set search_path='' as $$
 select jsonb_build_object('referral',(select jsonb_build_object('code',a.code,'creator_name',coalesce(c.published->>'nickname',c.draft->>'nickname',a.code),'created_at',a.created_at) from public.referral_attributions a left join public.creator_landings c on c.user_id=a.partner_id where a.user_id=p_user));
$$;
create or replace function public.efir_referral_claim(p_user uuid,p_code text,p_device_hash text default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare existing public.referral_attributions; owner_id uuid; nickname text; code_value text:=lower(trim(p_code));
begin
 if p_user is null or code_value is null or code_value !~ '^[a-z0-9][a-z0-9_-]{2,39}$' or (p_device_hash is not null and p_device_hash !~ '^[a-f0-9]{64}$') then raise exception 'REFERRAL_INVALID'; end if;
 perform pg_advisory_xact_lock(hashtextextended('referral:'||p_user::text,0));
 select * into existing from public.referral_attributions where user_id=p_user;
 if found then
  if existing.code<>code_value then raise exception 'REFERRAL_ALREADY_CLAIMED'; end if;
  return jsonb_build_object('ok',true,'code',existing.code,'already_claimed',true,'creator_name',(select coalesce(published->>'nickname',draft->>'nickname',existing.code) from public.creator_landings where user_id=existing.partner_id));
 end if;
 select c.user_id,c.published->>'nickname' into owner_id,nickname from public.creator_landings c where c.published->>'slug'=code_value;
 if owner_id=p_user then raise exception 'REFERRAL_SELF'; end if;
 if owner_id is null then raise exception 'REFERRAL_INVALID';end if;
 -- Share the existing landing lock with publication/access changes, then the partner row
 -- with admin suspension. Recheck after waiting so a stale slug cannot be claimed.
 perform pg_advisory_xact_lock(hashtextextended('landing:'||owner_id::text,0));
 perform 1 from public.referral_partners where user_id=owner_id for update;
 if not public.referral_partner_active(owner_id) or not exists(select 1 from public.creator_landings where user_id=owner_id and published->>'slug'=code_value) then raise exception 'REFERRAL_INVALID'; end if;
 insert into public.referral_attributions(user_id,partner_id,code,device_hash) values(p_user,owner_id,code_value,p_device_hash);
 return jsonb_build_object('ok',true,'code',code_value,'creator_name',nickname,'already_claimed',false);
end $$;

-- Resolve each authenticated payment once. Claims made after payment never backfill earnings.
-- An unlinked Telegram payment is retained until its verified account link arrives.
create or replace function public.referral_settle_payment(p_key text) returns void language plpgsql security definer set search_path='' as $$
declare payment public.referral_payments; attribution public.referral_attributions; buyer uuid; rate integer;
begin
 select * into payment from public.referral_payments where payment_key=p_key for update;
 if not found or payment.resolution<>'unlinked' then return; end if;
 select user_id into buyer from public.launcher_telegram_links where telegram_id=payment.telegram_id;
 if buyer is null then return; end if;
 select * into attribution from public.referral_attributions where user_id=buyer and created_at<=payment.paid_at;
 if not found then update public.referral_payments set buyer_id=buyer,resolution='no_prior_referral' where payment_key=p_key;return;end if;
 perform pg_advisory_xact_lock(hashtextextended('landing:'||attribution.partner_id::text,0));
 perform 1 from public.referral_partners where user_id=attribution.partner_id for update;
 if not public.referral_partner_active(attribution.partner_id) then update public.referral_payments set buyer_id=buyer,resolution='partner_inactive' where payment_key=p_key;return;end if;
 select coalesce(
  (select h.rate_bps from public.referral_rate_history h where h.partner_id=attribution.partner_id and h.changed_at<=payment.received_at order by h.changed_at desc,h.id desc limit 1),
  (select h.rate_bps from public.referral_rate_history h where h.partner_id is null and h.changed_at<=payment.received_at order by h.changed_at desc,h.id desc limit 1)
 ) into rate;
 if rate is null then raise exception 'RATE_HISTORY_MISSING';end if;
 update public.referral_payments set buyer_id=buyer,partner_id=attribution.partner_id,code=attribution.code,rate_bps=rate,commission=round(gross_amount*rate/10000,2),resolution='credited' where payment_key=p_key;
end $$;
create or replace function public.referral_link_settle() returns trigger language plpgsql security definer set search_path='' as $$
declare item record;
begin
 for item in select payment_key from public.referral_payments where telegram_id=new.telegram_id and resolution='unlinked' order by payment_key loop perform public.referral_settle_payment(item.payment_key);end loop;
 return new;
end $$;
drop trigger if exists referral_link_settle on public.launcher_telegram_links;
create trigger referral_link_settle after insert or update on public.launcher_telegram_links for each row execute function public.referral_link_settle();

-- This wrapper preserves entitlement ordering while independently retaining every paid period.
create or replace function public.efir_tribute_apply_paid(p_telegram text,p_subscription text,p_expires timestamptz,p_event_at timestamptz,p_key text,p_kind text,p_payment_key text,p_period text,p_gross_minor numeric,p_net_minor numeric,p_currency text) returns boolean language plpgsql security definer set search_path='' as $$
declare changed boolean; existing public.referral_payments;
begin
 if p_kind not in ('new_subscription','renewed_subscription') or p_kind is null or p_payment_key is null or p_payment_key !~ '^[a-f0-9]{64}$' or p_period is null or p_period !~ '^[1-9][0-9]*$'
 or p_gross_minor is null or p_gross_minor<=0 or p_gross_minor<>trunc(p_gross_minor) or p_gross_minor>9007199254740991
 or p_net_minor is null or p_net_minor<0 or p_net_minor<>trunc(p_net_minor) or p_net_minor>p_gross_minor or p_currency is null or p_currency not in ('EUR','USD','RUB') then raise exception 'INVALID_PAID_EVENT';end if;
 changed:=public.efir_tribute_apply(p_telegram,p_subscription,p_expires,p_event_at,p_key,p_kind);
 insert into public.referral_payments(payment_key,telegram_id,subscription_id,period_id,paid_at,expires_at,gross_amount,net_amount,currency)
 values(p_payment_key,p_telegram,p_subscription,p_period,p_event_at,p_expires,p_gross_minor/100,p_net_minor/100,p_currency) on conflict do nothing;
 select * into existing from public.referral_payments where payment_key=p_payment_key for update;
 if existing.telegram_id<>p_telegram or existing.subscription_id<>p_subscription or existing.period_id<>p_period or existing.expires_at<>p_expires or existing.gross_amount<>p_gross_minor/100 or existing.net_amount<>p_net_minor/100 or existing.currency<>p_currency then raise exception 'PAYMENT_CONFLICT';end if;
 perform public.referral_settle_payment(p_payment_key);
 return changed;
end $$;

create or replace function public.referral_partner_summary(p_user uuid) returns jsonb language sql stable security definer set search_path='' as $$
 select jsonb_build_object('user_id',p.user_id,'email',u.email,'slug',c.published->>'slug','name',coalesce(c.published->>'nickname',c.draft->>'nickname',''),
 'enabled',p.enabled,'active',public.referral_partner_active(p.user_id),'rate_bps',p.rate_bps,'effective_rate_bps',coalesce(p.rate_bps,s.rate_bps),'note',p.note,'revision',p.revision,
 'visitor_count',coalesce((select sum(hits) from public.landing_daily_stats where user_id=p.user_id and button_id='__referral_home'),0),
 'page_view_count',coalesce((select sum(hits) from public.landing_daily_stats where user_id=p.user_id and button_id=''),0),
 'referred_count',(select count(*) from public.referral_attributions where partner_id=p.user_id),
 'paying_count',(select count(distinct buyer_id) from public.referral_payments where partner_id=p.user_id),
 'balances',coalesce((select jsonb_agg(jsonb_build_object('currency',currency,'earned',earned,'paid',paid,'balance',earned-paid) order by currency) from (
 select currencies.currency,coalesce((select sum(commission-reversed) from public.referral_payments q where q.partner_id=p.user_id and q.currency=currencies.currency),0) earned,
 coalesce((select sum(amount) from public.referral_payouts q where q.partner_id=p.user_id and q.currency=currencies.currency),0) paid
 from (select currency from public.referral_payments where partner_id=p.user_id union select currency from public.referral_payouts where partner_id=p.user_id) currencies) totals),'[]'::jsonb))
 from public.referral_partners p join auth.users u on u.id=p.user_id left join public.creator_landings c on c.user_id=p.user_id cross join public.referral_settings s where p.user_id=p_user and s.id;
$$;
create or replace function public.admin_referral_list(p_search text default '',p_offset integer default 0) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb;
begin
 if not public.is_efir_admin() then raise exception 'ADMIN_REQUIRED' using errcode='42501';end if;
 if p_offset is null or p_offset<0 then raise exception 'INVALID_OFFSET';end if;
 with rows as (select p.user_id from public.referral_partners p join auth.users u on u.id=p.user_id left join public.creator_landings c on c.user_id=p.user_id where lower(coalesce(u.email,'')||' '||p.user_id::text||' '||coalesce(c.published->>'slug','')||' '||coalesce(c.draft->>'nickname','')) like '%'||lower(trim(coalesce(p_search,'')))||'%')
 select jsonb_build_object('total',(select count(*) from rows),'default_rate_bps',(select rate_bps from public.referral_settings where id),'settings_revision',(select revision from public.referral_settings where id),'items',coalesce((select jsonb_agg(public.referral_partner_summary(r.user_id)) from (select user_id from rows order by user_id limit 50 offset p_offset) r),'[]'::jsonb)) into result;
 return result;
end $$;
create or replace function public.admin_referral_detail(p_user_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb;
begin
 if not public.is_efir_admin() then raise exception 'ADMIN_REQUIRED' using errcode='42501';end if;
 result:=public.referral_partner_summary(p_user_id);if result is null then raise exception 'NOT_FOUND';end if;
 return result||jsonb_build_object('commissions',coalesce((select jsonb_agg(r) from (select q.payment_key,q.buyer_id,q.code,q.paid_at,q.gross_amount,q.net_amount,q.currency,q.rate_bps,q.commission,q.reversed,q.resolution,exists(select 1 from public.referral_reversals v where v.payment_key=q.payment_key) is_reversed from public.referral_payments q where q.partner_id=p_user_id order by q.paid_at desc limit 100) r),'[]'::jsonb),
 'payouts',coalesce((select jsonb_agg(r) from (select * from public.referral_payouts where partner_id=p_user_id order by created_at desc limit 100) r),'[]'::jsonb),
 'referrals',coalesce((select jsonb_agg(r) from (select a.user_id,u.email,a.code,a.created_at,exists(select 1 from public.referral_attributions d where d.device_hash=a.device_hash and d.user_id<>a.user_id) device_reused from public.referral_attributions a join auth.users u on u.id=a.user_id where a.partner_id=p_user_id order by a.created_at desc limit 100) r),'[]'::jsonb));
end $$;
create or replace function public.referral_dashboard() returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb;
begin
 result:=public.referral_partner_summary(auth.uid());
 if result is null then return jsonb_build_object('allowed',false);end if;
 return (result-'email'-'note')||jsonb_build_object('allowed',true,'payouts',coalesce((select jsonb_agg(r) from (select currency,amount,created_at from public.referral_payouts where partner_id=auth.uid() order by created_at desc limit 100) r),'[]'::jsonb));
end $$;
create or replace function public.admin_referral_save(p_user_id uuid,p_enabled boolean,p_rate_bps integer,p_note text,p_revision integer) returns jsonb language plpgsql security definer set search_path='' as $$
declare old public.referral_partners;
begin
 if not public.is_efir_admin() then raise exception 'ADMIN_REQUIRED' using errcode='42501';end if;
 if p_enabled is null or (p_rate_bps is not null and p_rate_bps not between 0 and 10000) or p_note is null or length(p_note)>2000 then raise exception 'INVALID_PARTNER';end if;
 select * into old from public.referral_partners where user_id=p_user_id for update;
 if not found then raise exception 'NOT_FOUND';end if;
 if old.revision is distinct from p_revision then raise exception 'DATA_CHANGED';end if;
 update public.referral_partners set enabled=p_enabled,rate_bps=p_rate_bps,note=p_note,revision=revision+1 where user_id=p_user_id;
 insert into public.admin_audit_log(admin_user_id,target_user_id,action,details) values(auth.uid(),p_user_id,'referral_partner_save',jsonb_build_object('before',to_jsonb(old),'enabled',p_enabled,'rate_bps',p_rate_bps,'note',p_note));
 return public.referral_partner_summary(p_user_id);
end $$;
create or replace function public.admin_referral_settings(p_rate_bps integer,p_revision integer) returns jsonb language plpgsql security definer set search_path='' as $$
declare old public.referral_settings;
begin
 if not public.is_efir_admin() then raise exception 'ADMIN_REQUIRED' using errcode='42501';end if;
 if p_rate_bps is null or p_rate_bps not between 0 and 10000 then raise exception 'INVALID_RATE';end if;
 select * into old from public.referral_settings where id for update;
 if old.revision is distinct from p_revision then raise exception 'DATA_CHANGED';end if;
 update public.referral_settings set rate_bps=p_rate_bps,revision=revision+1 where id;
 insert into public.admin_audit_log(admin_user_id,action,details) values(auth.uid(),'referral_settings',jsonb_build_object('before',to_jsonb(old),'rate_bps',p_rate_bps));
 return (select to_jsonb(s) from public.referral_settings s where id);
end $$;
create or replace function public.admin_referral_payout(p_user_id uuid,p_currency text,p_amount numeric,p_note text,p_idempotency uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare existing public.referral_payouts; available numeric; currency_value text:=upper(p_currency);
begin
 if not public.is_efir_admin() then raise exception 'ADMIN_REQUIRED' using errcode='42501';end if;
 if p_idempotency is null or p_amount is null or p_amount<=0 or p_amount<>round(p_amount,2) or currency_value is null or currency_value not in ('EUR','USD','RUB') or p_note is null or length(trim(p_note)) not between 1 and 2000 then raise exception 'INVALID_PAYOUT';end if;
 perform pg_advisory_xact_lock(hashtextextended('referral-payout:'||p_idempotency::text,0));
 select * into existing from public.referral_payouts where id=p_idempotency;
 if found then
  if existing.partner_id<>p_user_id or existing.currency<>currency_value or existing.amount<>p_amount or existing.note<>trim(p_note) then raise exception 'IDEMPOTENCY_CONFLICT';end if;
  return to_jsonb(existing);
 end if;
 perform 1 from public.referral_partners where user_id=p_user_id for update;if not found then raise exception 'NOT_FOUND';end if;
 select coalesce((select sum(commission-reversed) from public.referral_payments where partner_id=p_user_id and currency=currency_value),0)-coalesce((select sum(amount) from public.referral_payouts where partner_id=p_user_id and currency=currency_value),0) into available;
 if p_amount>available then raise exception 'INSUFFICIENT_BALANCE';end if;
 insert into public.referral_payouts(id,partner_id,currency,amount,note,admin_user_id) values(p_idempotency,p_user_id,currency_value,p_amount,trim(p_note),auth.uid()) returning * into existing;
 insert into public.admin_audit_log(admin_user_id,target_user_id,action,details) values(auth.uid(),p_user_id,'referral_payout',to_jsonb(existing));
 return to_jsonb(existing);
end $$;
-- Subscription cancellation merely stops renewal; refunds require an explicitly recorded adjustment.
-- A post-payout refund may make a balance negative, carried into later earnings.
create or replace function public.admin_referral_reverse(p_payment_key text,p_note text,p_idempotency uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare payment public.referral_payments; existing public.referral_reversals;
begin
 if not public.is_efir_admin() then raise exception 'ADMIN_REQUIRED' using errcode='42501';end if;
 if p_idempotency is null or p_note is null or length(trim(p_note)) not between 1 and 2000 then raise exception 'INVALID_REVERSAL';end if;
 perform pg_advisory_xact_lock(hashtextextended('referral-reversal:'||p_idempotency::text,0));
 select * into existing from public.referral_reversals where id=p_idempotency;
 if found then if existing.payment_key<>p_payment_key or existing.note<>trim(p_note) then raise exception 'IDEMPOTENCY_CONFLICT';end if;return to_jsonb(existing);end if;
 select * into payment from public.referral_payments where payment_key=p_payment_key for update;
 if not found or payment.partner_id is null then raise exception 'NOT_FOUND';end if;
 perform 1 from public.referral_partners where user_id=payment.partner_id for update;
 if exists(select 1 from public.referral_reversals where payment_key=p_payment_key) then raise exception 'ALREADY_REVERSED';end if;
 insert into public.referral_reversals(id,payment_key,amount,note,admin_user_id) values(p_idempotency,p_payment_key,payment.commission,trim(p_note),auth.uid()) returning * into existing;
 update public.referral_payments set reversed=commission where payment_key=p_payment_key;
 insert into public.admin_audit_log(admin_user_id,target_user_id,action,details) values(auth.uid(),payment.partner_id,'referral_refund',to_jsonb(existing));
 return to_jsonb(existing);
end $$;

revoke all on function public.referral_landing_access_sync(),public.referral_partner_active(uuid),public.efir_referral_status(uuid),public.efir_referral_claim(uuid,text,text),public.referral_settle_payment(text),public.referral_link_settle(),public.referral_partner_summary(uuid),public.efir_tribute_apply_paid(text,text,timestamptz,timestamptz,text,text,text,text,numeric,numeric,text),public.admin_referral_list(text,integer),public.admin_referral_detail(uuid),public.referral_dashboard(),public.admin_referral_save(uuid,boolean,integer,text,integer),public.admin_referral_settings(integer,integer),public.admin_referral_payout(uuid,text,numeric,text,uuid),public.admin_referral_reverse(text,text,uuid) from public,anon,authenticated;
revoke all on function public.referral_rate_track() from public,anon,authenticated;
grant execute on function public.efir_referral_status(uuid),public.efir_referral_claim(uuid,text,text),public.efir_tribute_apply_paid(text,text,timestamptz,timestamptz,text,text,text,text,numeric,numeric,text) to service_role;
grant execute on function public.admin_referral_list(text,integer),public.admin_referral_detail(uuid),public.referral_dashboard(),public.admin_referral_save(uuid,boolean,integer,text,integer),public.admin_referral_settings(integer,integer),public.admin_referral_payout(uuid,text,numeric,text,uuid),public.admin_referral_reverse(text,text,uuid) to authenticated;
commit;
